name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main
      - releases/**
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Install flatc
        run: |
          wget https://github.com/google/flatbuffers/releases/download/v23.5.26/Linux.flatc.binary.g++-10.zip
          unzip Linux.flatc.binary.g++-10.zip
          chmod +x flatc
          sudo cp flatc /usr/bin
      - uses: actions/setup-java@v3.11.0
        with:
          java-version: '20.0.1'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.5
      - name: Publish package
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}