name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main
      - releases/**
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Install flatc
        run: |
          sudo apt-get update
          sudo apt install -y flatbuffers-compiler
      - uses: actions/setup-java@v3.9.0
        with:
          java-version: '19.0.2'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.5
      - name: Publish package
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}